version: '3.4'

services:

  database:
    container_name: db
    image: mysql:8.0.22
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: suasenha
    networks:
      - turismo-network

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    depends_on: 
      - database
    ports: 
      - "2000:80"
    environment: 
      - DBHOST=db
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - turismo-network

  frontend:
    container_name: frontend
    build: ./frontend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app/frontend
    networks:
      - turismo-network

volumes:
  db:

networks:
  turismo-network:
    driver: bridge